spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: auth-service

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

application:
  title: Authentication Service API

