server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb:http://user-service
          predicates:
            - Path=/api/v1/users/**
  logging:
    level:
      org.springframework.cloud.gateway: DEBUG
