spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: engineers.newgeneration@gmail.com
    password: qxzhhqontwiwjmnn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/user
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 8090

application:
  security:
    jwt:
      secret-key: 49b6a6cb88892292be99b690e3cbb059b71e0cfa3bd14b426adccbcc3630f7b6
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:8081/activate-account