CREATE TABLE IF NOT EXISTS token (
    id VARCHAR(255) PRIMARY KEY,
    token VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expired_at TIMESTAMPTZ,
    validated_at TIMESTAMPTZ,
    user_id VARCHAR(255) NOT NULL
);
